import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function encrypt(plaintext, password) {
  const salt = crypto.randomBytes(16);
  const key = crypto.pbkdf2Sync(password, salt, 100_000, 32, 'sha256');
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();

  return {
    ciphertext: ciphertext.toString('hex'),
    iv: iv.toString('hex'),
    salt: salt.toString('hex'),
    tag: tag.toString('hex'),
  };
}

const [, , content, password] = process.argv;
if (!content || !password) {
  console.error('Usage: node scripts/encrypt-content.mjs "<secret content>" "<password>"');
  process.exit(1);
}

const result = encrypt(content, password);
const tsCode = `// Auto-generated by encrypt-content.mjs — DO NOT EDIT
// Re-generate with: npm run encrypt:content

export const ENCRYPTED_SECRET = {
  ciphertext: "${result.ciphertext}",
  iv: "${result.iv}",
  salt: "${result.salt}",
  tag: "${result.tag}",
} as const;
`;

const outPath = path.resolve(__dirname, '..', 'src', 'lib', 'secure', 'encrypted-data.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, tsCode);
console.log(`\u2705 Encrypted data written to ${outPath}`);
console.log(`\u26a0\ufe0f  Use URL: https://yoursite.com/secret#${password}`);
