import re

def optimize_pixels(art_str, color_map):
    lines = [line for line in art_str.strip().split('\n') if line]
    if not lines: return []
    
    pixels = []
    height = len(lines)
    width = len(lines[0])
    
    for y in range(height):
        x = 0
        while x < width:
            char = lines[y][x]
            if char != '.' and char != ' ':
                start_x = x
                while x < width and lines[y][x] == char:
                    x += 1
                w = x - start_x
                color = color_map.get(char, char)
                pixels.append((start_x, y, w, 1, color))
            else:
                x += 1
                
    optimized = []
    used = set()
    for i, p1 in enumerate(pixels):
        if i in used: continue
        x1, y1, w1, h1, c1 = p1
        curr_h = h1
        
        for j in range(i + 1, len(pixels)):
            if j in used: continue
            x2, y2, w2, h2, c2 = pixels[j]
            if x1 == x2 and w1 == w2 and c1 == c2 and y2 == y1 + curr_h:
                curr_h += h2
                used.add(j)
        
        optimized.append((x1, y1, w1, curr_h, c1))
        
    return optimized

def print_pixels(pixels):
    out = "    <PixelBlocks\n      pixels={[\n"
    for p in pixels:
        x, y, w, h, c = p
        if w == 1 and h == 1:
            out += f"        [{x}, {y}, '{c}'],\n"
        else:
            out += f"        [{x}, {y}, {w}, {h}, '{c}'],\n"
    out += "      ]}\n    />\n"
    return out

ICONS = {}

# 1. EnergyIcon (Lightbulb)
ICONS['EnergyIcon'] = {
    'map': {
        'O': '#EA580C', # Dark Orange outline
        'Y': '#FBBF24', # Yellow bright
        'M': '#F59E0B', # Medium orange
        'W': '#FFFFFF', # White highlight
        'D': '#1E3A8A', # Dark blue base
        'B': '#3B82F6', # Blue base
        'G': '#475569', # Grey base
        'N': '#F97316', # Inner N color
    },
    'art': """
........OOOO........
......OOYYYYOO......
.....OYYYYYYYYO.....
....OYYYWWWYYYYO....
....OYYYWWWYYYYO....
...OYYWWNWWNYYYYO...
...OYYWNNWNNWYYYO...
...OYYWNWNWNWYYYO...
...OYYWWNWWNYYYYO...
....OYYYWWWWYYYO....
....OYYYMMMMYYYO....
.....OYYMMMMYYO.....
......OOMMMMOO......
.......OGGGGO.......
.......GDDDDG.......
.......GDWWDG.......
.......GDBBDG.......
........GDDG........
........GGGG........
.........GG.........
"""
}

# 2. RoboticsIcon (Robot Arm)
ICONS['RoboticsIcon'] = {
    'map': {
        'L': '#93C5FD', # Light Blue
        'B': '#3B82F6', # Blue
        'W': '#FFFFFF', # White
        'G': '#CBD5E1', # Light Grey
        'D': '#64748B', # Dark Grey
        'O': '#F97316', # Orange
    },
    'art': """
......WWWWWW........
.....WWWWWWWW.......
....WWWWWWWWWW......
....WWWWLLWWWW......
....WWWW..WWWW......
....WWWW..WWWW......
....WWWW..WWWW......
....WWWW..WWWW......
.....WW....WW.......
.....W......W.......
....OOOO............
...OWWWWO...........
...OOWWOO...........
.....BB.............
.....BB.............
.....BB.............
.....BB.............
....GGGG............
...GWWWWG...........
..GWWWWWWG..........
"""
}

# 3. ClinicalIcon (Flask)
ICONS['ClinicalIcon'] = {
    'map': {
        'P': '#EC4899', # Pink
        'R': '#BE185D', # Dark Pink / Red
        'O': '#F97316', # Orange
        'Y': '#FBBF24', # Yellow
        'W': '#FFFFFF', # White
        'B': '#3B82F6', # Blue smoke
        'L': '#93C5FD', # Light blue smoke
    },
    'art': """
........WWWW........
.......WLLLLW.......
......WLLBBLLW......
.......WLBBW........
........WWWW........
.........WW.........
.........WW.........
........WWWW........
........WYYW........
.......WYYYYW.......
.......WYYYYW.......
......WYYOOYYW......
......WYYOOYYW......
.....WYYOPPOYYW.....
.....WYYPPPOYYW.....
....WYYPPPPPOYYW....
....WYYPRRRPPOYW....
...WYYYPRRRRPOYYW...
...WWWWWWWWWWWWWW...
....................
"""
}

# 4. LlmIcon (Translation/Knowledge Blocks)
ICONS['LlmIcon'] = {
    'map': {
        'D': '#1E3A8A', # Dark Blue
        'B': '#3B82F6', # Blue
        'L': '#93C5FD', # Light Blue
        'O': '#EA580C', # Dark Orange
        'M': '#F59E0B', # Medium orange
        'Y': '#FBBF24', # Yellow
        'W': '#FFFFFF', # White
        'N': '#F97316', # Inner N color
    },
    'art': """
..........OOO.......
.........OMMMO......
........OMYYYYO.....
.......OMYWWWWYO....
.......OMYWWWWYO....
.......OMYWWWWYO....
......OMMYWWWWYMO...
....DDDDMYWWWWYMD...
...DBBBBDMYYYYMD....
..DBLLLLBDMMMMD.....
.DBLWWWWLBDDD.......
.DBLWWWWLBD.........
.DBLNWNWLBD.........
.DBLNNWNLBD.........
.DBLNWNWLBD.........
.DBLNWNWLBD.........
.DBLWWWWLBD.........
..DBLLLLBD..........
...DBBBBD...........
....DDDD............
"""
}

# 5. BlogIcon (Book/Document)
ICONS['BlogIcon'] = {
    'map': {
        'D': '#1E3A8A', # Dark Blue
        'B': '#3B82F6', # Blue
        'L': '#93C5FD', # Light Blue
        'W': '#FFFFFF', # White
        'R': '#EF4444', # Red bookmark
        'P': '#FCA5A5', # Light red
        'N': '#3B82F6', # Inner N color
    },
    'art': """
......DDDDDDDD......
.....DBBBBBBBBD.....
....DBLLLLLLLLBD....
....DBLWWWWWWLBD....
....DBLWWWWWWLBD....
....DBLWWNWWNLBD....
....DBLWNNWNNLBD....
....DBLWNWNWNLBD....
....DBLWWNWWNLBD....
....DBLWWWWWWLBD....
....DBLWWWWWWLBD....
....DBLWWWWWWLBD....
....DBLLLLLLLLBD....
...DBBBBBBBBBBBBD...
..DDDDDDDDDDDDDDDD..
..DWWWWWWWWWWWWWWD..
..DDDDDDDDDDDDDDDD..
........RRPP........
........RRRR........
.........RR.........
"""
}

# 6. DiscordIcon (Speech Bubble/Controller)
ICONS['DiscordIcon'] = {
    'map': {
        'P': '#7C3AED', # Purple Dark
        'M': '#8B5CF6', # Purple Medium
        'L': '#A78BFA', # Purple Light
        'W': '#FFFFFF', # White
    },
    'art': """
......PPPPPPPP......
....PPMMMMMMMMPP....
...PMMLLLLLLLLMMP...
..PMMLLLLLLLLLLMMP..
..PMLLLLLLLLLLLLMP..
..PMLLWWLLLLWWLLMP..
.PMMLLWWLLLLWWLLMMP.
.PMMLLWWLLLLWWLLMMP.
.PMMLLLLLLLLLLLLMMP.
.PMMLLLLWWWWLLLLMMP.
.PMMLLWWLLLLWWLLMMP.
..PMLLLWWWWWWLLLMP..
..PMMLLLLLLLLLLMMP..
...PMMMMMMMMMMMMP...
....PPPPPPPPPPPP....
.....PP......PP.....
....PP........PP....
...PP..........PP...
....................
....................
"""
}

# 7. EventsIcon (Calendar)
ICONS['EventsIcon'] = {
    'map': {
        'R': '#EF4444', # Red
        'D': '#B91C1C', # Dark Red
        'W': '#FFFFFF', # White
        'G': '#E2E8F0', # Light Grey
        'B': '#94A3B8', # Grey
        'O': '#0F172A', # Dark border
        'N': '#3B82F6', # Inner N color
    },
    'art': """
....BB........BB....
....BB........BB....
..OOBBOOOOOOOOBBOO..
..ODDRRDDDDDDRRDDO..
..ORRRRRRRRRRRRRRO..
..ODDDDDDDDDDDDDDO..
..OWWWWWWWWWWWWWWO..
..OWGGGGGGGGGGGGWO..
..OWGGGGGGGGGGGGWO..
..OWGGWNNWWNNWGGWO..
..OWGGWNNNWNNWGGWO..
..OWGGWNWNWNWWGGWO..
..OWGGWNNWWNNWGGWO..
..OWGGWWWWWWWWGGWO..
..OWGGGGGGGGGGGGWO..
..OWGGGGGGGGGGGGWO..
..OWWWWWWWWWWWWWWO..
..OOOOOOOOOOOOOOOO..
....................
....................
"""
}

# 8. AboutIcon (Institution/Building)
ICONS['AboutIcon'] = {
    'map': {
        'B': '#3B82F6', # Blue
        'L': '#93C5FD', # Light Blue
        'D': '#1E3A8A', # Dark Blue
        'W': '#FFFFFF', # White
        'G': '#CBD5E1', # Grey
        'R': '#EF4444', # Red Flag
    },
    'art': """
.........RRR........
.........RRR........
.........LWW........
.........LWW........
.......DDLLDD.......
......DLLWWLLD......
.....DLLLWWLLLD.....
....DDDDDDDDDDDD....
....DWWWWWWWWWWD....
....DDDDDDDDDDDD....
.....DWWDWWDWWD.....
.....DWWDWWDWWD.....
.....DWWDWWDWWD.....
.....DWWDWWDWWD.....
.....DWWDWWDWWD.....
....DDDDDDDDDDDD....
...DLLLLLLLLLLLLD...
..DDDDDDDDDDDDDDDD..
....................
....................
"""
}

# 9. CareersIcon (Briefcase)
ICONS['CareersIcon'] = {
    'map': {
        'B': '#92400E', # Dark Brown
        'M': '#B45309', # Medium Brown
        'L': '#D97706', # Light Brown
        'W': '#FDE68A', # Yellowish White
        'N': '#F97316', # Inner N color
    },
    'art': """
........BBBB........
.......BWWGGB.......
.......BWBBWB.......
.......BWBBWB.......
..BBBBBBBBBBBBBBBB..
..BMMMMMMMMMMMMMMB..
..BMLLLLLLLLLLLLMB..
..BMLWWWWWWWWWWLMB..
..BMLWWWWWWWWWWLMB..
..BMLWWNWNWWNWLMBB..
..BMLWWNWNNWNWLMBB..
..BMLWWNWWNWNWLMBB..
..BMLWWNWNWWNWLMBB..
..BMLWWWWWWWWWWLMB..
..BMLWWWWWWWWWWLMB..
..BMLLLLLLLLLLLLMB..
..BMMMMMMMMMMMMMMB..
..BBBBBBBBBBBBBBBB..
....................
....................
"""
}

# 10. AssistantIcon (Terminal Window)
ICONS['AssistantIcon'] = {
    'map': {
        'D': '#1E3A8A', # Dark Blue border
        'B': '#0F172A', # Black/Dark background
        'L': '#3B82F6', # Blue title bar
        'R': '#EF4444', # Red button
        'Y': '#FBBF24', # Yellow button
        'G': '#10B981', # Green button
        'W': '#FFFFFF', # White text
        'O': '#F97316', # Orange N
    },
    'art': """
....................
..DDDDDDDDDDDDDDDD..
..DLLLLLLLLLLLLLLD..
..DLRRYYGGLLLLLLLD..
..DLLLLLLLLLLLLLLD..
..DDDDDDDDDDDDDDDD..
..DBBBBBBBBBBBBBBD..
..DBBBBBBBBBBBBBBD..
..DBBBBBBBBBBBBBBD..
..DBBBWOOWWBBBBBBD..
..DBBBWWOWWBBBBBBD..
..DBBBWWOWWBBBBBBD..
..DBBBWWWOOWBBBBBD..
..DBBBBBBBBBBBBBBD..
..DBBBBBBBBBBBBBBD..
..DBBBWWBBBBBBBBBD..
..DBBBBBBBBBBBBBBD..
..DDDDDDDDDDDDDDDD..
....................
....................
"""
}

# 11. DeploymentIcon (Server Rack)
ICONS['DeploymentIcon'] = {
    'map': {
        'L': '#CBD5E1', # Light Grey Chassis
        'G': '#94A3B8', # Grey border
        'D': '#334155', # Dark Grey slot
        'B': '#3B82F6', # Blue light
        'Y': '#FBBF24', # Yellow light
        'W': '#FFFFFF', # White light
        'O': '#F97316', # Orange
    },
    'art': """
....................
....GGGGGGGGGGGG....
...GLLLLLLLLLLLLG...
...GLDDDDDDDDDDLG...
...GLDDBBDWYDDDLG...
...GLDDDDDDDDDDLG...
...GLLLLLLLLLLLLG...
...GLDDDDDDDDDDLG...
...GLDDBBDWYDDDLG...
...GLDDDDDDDDDDLG...
...GLLLLLLLLLLLLG...
...GLDDDDDDDDDDLG...
...GLDDBBDWYDDDLG...
...GLDDDDDDDDDDLG...
...GLLLLLLLLLLLLG...
...GLDDDDDDDDDDLG...
...GLDDOODWYDDDLG...
...GLDDDDDDDDDDLG...
...GLLLLLLLLLLLLG...
....GGGGGGGGGGGG....
"""
}

# 12. ContactIcon (Envelope/Mail)
ICONS['ContactIcon'] = {
    'map': {
        'B': '#3B82F6', # Blue
        'L': '#93C5FD', # Light Blue
        'D': '#1E3A8A', # Dark Blue
        'W': '#FFFFFF', # White
        'G': '#E2E8F0', # Very light blue/grey
    },
    'art': """
....................
..DDDDDDDDDDDDDDDD..
..DBBBBBBBBBBBBBBD..
..DBLLLLLLLLLLLLBD..
..DBLWWWWWWWWWWLBD..
..DBLWWWWWWWWWWLBD..
..DBLLWWWWWWWWLLBD..
..DBLLLWWWWWWLLLBD..
..DBLLLLWWWWLLLLBD..
..DBLLLLLWWLLLLLBD..
..DBLLLLLLLLLLLLBD..
..DBBBBBBBBBBBBBBD..
..DDDDDDDDDDDDDDDD..
....................
....................
....................
....................
....................
....................
....................
"""
}

def generate_all():
    with open("C:/Users/Hellx/Documents/Programming/python/Project/Neryva/neryva-website/scratch/generated_icons.tsx", "w") as f:
        for name, data in ICONS.items():
            f.write(f"function {name}() {{\n  return (\n")
            pixels = optimize_pixels(data['art'], data['map'])
            f.write(print_pixels(pixels))
            f.write("  );\n}\n\n")
    print("Icons generated in scratch/generated_icons.tsx")

if __name__ == '__main__':
    generate_all()
